### ISSUE TITLE
g10k crash constantly after deploy error

### ISSUE THREAD

**Issue by baurmatt** [xorpaul/g10k#128]
I did a complete new g10k run (no caches, ...) which failed for $reasons:

```
$ ./g10k -config g10k.yaml
Resolving Forge modules (112/112)    6s [====================================================================] 100%
Resolving Git modules (77/77)   29s [====================================================================] 100%
executeCommand(): git command failed: git --git-dir /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppet-python.git rev-parse --verify '1d90a191bf5bb077738dee1f255ca6d38857f72f^{object}' exit status 128
Output: fatal: Needed a single revision

If you are using GitLab please ensure that you've added your deploy key to your repository
```
After this, every g10k run will fail with this error message:
```
$ ./g10k -config g10k.yaml
2019/04/26 11:13:00 createOrPurgeDir(): error: removing dir faileddirectory not empty
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12b9466]

goroutine 121 [running]:
main.unTar(0x13e43a0, 0xc000228138, 0xc000605520, 0x1f)
	/home/andpaul/dev/go/src/github.com/xorpaul/g10k/forge.go:396 +0x506
main.syncToModuleDir(0xc000158080, 0x32, 0xc000605520, 0x1f, 0xc00018a2bf, 0x5, 0x0, 0xc000668d65, 0x5, 0xc000605400)
	/home/andpaul/dev/go/src/github.com/xorpaul/g10k/git.go:186 +0x835
main.resolvePuppetEnvironment.func1.1(0xc00011c620, 0x0, 0x0, 0x0, 0x0, 0xc000464bd0, 0xc00011a197, 0x9, 0xc000158080, 0x32, ...)
	/home/andpaul/dev/go/src/github.com/xorpaul/g10k/puppetfile.go:119 +0x503
created by main.resolvePuppetEnvironment.func1
	/home/andpaul/dev/go/src/github.com/xorpaul/g10k/puppetfile.go:87 +0x906
```

**Comment by xorpaul** [comment]
Please post the output with the `-debug` parameter.

**Comment by baurmatt** [comment]
Sure :)

[debug-log.txt](https://github.com/xorpaul/g10k/files/3121090/debug-log.txt)

**Comment by xorpaul** [comment]
Hmm, and what does the content of `/Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppet-python.git` look like on your system?

**Comment by baurmatt** [comment]
Looks "normal":

```
$ ls -la /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppet-python.git
total 20
drwxr-xr-x 10 mbaur staff  320 Apr 26 15:39 .
drwxr-xr-x 77 mbaur staff 2464 Apr 26 15:39 ..
-rw-r--r--  1 mbaur staff   23 Apr 26 15:39 HEAD
-rw-r--r--  1 mbaur staff  222 Apr 26 15:39 config
-rw-r--r--  1 mbaur staff   73 Apr 26 15:39 description
drwxr-xr-x 13 mbaur staff  416 Apr 26 15:39 hooks
drwxr-xr-x  3 mbaur staff   96 Apr 26 15:39 info
drwxr-xr-x  4 mbaur staff  128 Apr 26 15:39 objects
-rw-r--r--  1 mbaur staff 5841 Apr 26 15:39 packed-refs
drwxr-xr-x  4 mbaur staff  128 Apr 26 15:39 refs
```

**Comment by xorpaul** [comment]
I'm suspecting that one Git module repository on your system is in a corrupted state.

Could you check your local Git repository copies with:
`for i in /Users/mbaur/.g10-cache/modules/*.git ; do echo checking $i ; git --git-dir $i fsck --full ; done`

**Comment by baurmatt** [comment]
They look all good:

```
$ for i in /Users/mbaur/.g10-cache/modules/*.git ; do echo checking $i ; git --git-dir $i fsck --full ; done
checking /Users/mbaur/.g10-cache/modules/git@gitlab.example.org-puppet-manifests_syseleven-base.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (92813/92813), done.
checking /Users/mbaur/.g10-cache/modules/git@gitlab.example.org-puppet-manifests_syseleven-hieradata.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (551701/551701), done.
Checking connectivity: 551701, done.
checking /Users/mbaur/.g10-cache/modules/git@gitlab.example.org-puppet-manifests_syseleven-other.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (68387/68387), done.
checking /Users/mbaur/.g10-cache/modules/git@gitlab.example.org-puppet-manifests_syseleven-private.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (31162/31162), done.
checking /Users/mbaur/.g10-cache/modules/git@gitlab.example.org-puppet-manifests_syseleven-shared.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (6092/6092), done.
checking /Users/mbaur/.g10-cache/modules/https-__bitbucket.org_landcareresearch_puppet-solr.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (659/659), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_baurmatt_puppet-logstashforwarder.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (246/246), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_benibr_puppet-bareos.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (339/339), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_camptocamp_puppet-systemd.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1533/1533), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_cubiclelord_beanstalkd.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (258/258), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_maestrodev_puppet-wget.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1149/1149), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_mrszop_puppet-proxysql.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (637/637), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_puppet-community_puppet-unattended_upgrades.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1386/1386), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_puppetlabs_puppetlabs-apt.git
Checking object directories: 100% (256/256), done.
warning in tree 36264c41f53edfbbba234cc5ec8cb894a6ed6fdf: zeroPaddedFilemode: contains zero-padded file modes
Checking objects: 100% (8780/8780), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_puppetlabs_puppetlabs-concat.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (4662/4662), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_puppetlabs_puppetlabs-mysql.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (13562/13562), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_puppetlabs_puppetlabs-puppetdb.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (3500/3500), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_puppetlabs_puppetlabs-rsync.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1441/1441), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_puppetlabs_puppetlabs-tftp.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (643/643), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_puppetlabs_puppetlabs-tomcat.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (4407/4407), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_puppetlabs_puppetlabs-vcsrepo.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (6630/6630), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_puppetlabs_puppetlabs-xinetd.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1065/1065), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_stefanandres_puppet-pamldap.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (194/194), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_garethr-erlang.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (265/265), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppet-aptly.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1119/1119), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppet-elastic-stack.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (272/272), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppet-letsencrypt.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1709/1709), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppet-logstash-reporter.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (262/262), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppet-logstash.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (5034/5034), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppet-proxysql.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1737/1737), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppet-puppet.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (5092/5092), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppet-python.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (3305/3305), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppet-sudo.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1820/1820), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_syseleven_puppetlabs-rabbitmq.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (6429/6429), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_thias_puppet-sysctl.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (638/638), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_voxpupuli_puppet-extlib.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1589/1589), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_voxpupuli_puppet-letsencrypt.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (2041/2041), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_voxpupuli_puppet-nginx.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (15091/15091), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_voxpupuli_puppet-nodejs.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (3356/3356), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_voxpupuli_puppet-proxysql.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (2060/2060), done.
checking /Users/mbaur/.g10-cache/modules/https-__github.com_voxpupuli_puppet-zabbix.git
Checking object directories: 100% (256/256), done.
Checking objects: 100% (8084/8084), done.
```

**Comment by xorpaul** [comment]
Do you still experience these crashes?

You could also try out the new release https://github.com/xorpaul/g10k/releases/tag/v0.7.0

**Comment by baurmatt** [comment]
yep, that looks better. What ever you did, thanks a lot! :)
