### ISSUE TITLE
git archive untar hangs when trailing nuls in stream

### ISSUE THREAD

**Issue by juliantaylor** [xorpaul/g10k#98]
The golang tar package seems to sometimes leave trailing null bytes in the ioreader after it has encountered its `EOF`
This can lead to the process deadlocking as the git subprocess wants to write the remaining nuls to its stdout but g10k is not reading them anymore so it is blocking forever when the pipe buffer is full.

This is probably a bug in golangs tar library, though this patch could be used to work around it:

```patch
--- a/forge.go
+++ b/forge.go
@@ -358,6 +358,12 @@ func unTar(r io.Reader, targetBaseDir string) {
                        Fatalf(funcName + "(): Unable to untar type: " + string(header.Typeflag) + " in file " + filename)
                }
        }
+       buf := make([]byte, 4096)
+       nread, err := r.Read(buf)
+       for nread > 0 && err == nil {
+               Infof(fmt.Sprintf("Discarded %d bytes of trailing data", nread))
+               nread, err = r.Read(buf)
+       }
 }
 
 func downloadForgeModule(name string, version string, fm ForgeModule, retryCount int) {

**Comment by xorpaul** [comment]
With this patch I get unpopulated environments and failing tests:

```
                ./example/example_static/external_modules/cassandra/templates/cassandra1.yaml.erb: Known file not used                                                                                               
                ./example/example_static/external_modules/cassandra/templates/cassandra.yaml.erb: Known file not used                                                                                                
                hashdeep: Audit failed                                                                                                                                                                               
                   Input files examined: 0                                                                                                              
                  Known files expecting: 0                                                                                                          
                          Files matched: 12                                                                                                         
                Files partially matched: 0                                                                                                                                                                           
                            Files moved: 0                                                                                                                 
                        New files found: 0                                                                                                           
                  Known files not found: 5266                                                                                                                      
panic: runtime error: invalid memory address or nil pointer dereference [recovered]                                                                           
        panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                      
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6daf08]                                                                                             
                                                                                                                                                                        
goroutine 100 [running]:                                                                                                                                                                                             
testing.tRunner.func1(0xc42014e0f0)                                                                                                                      
        /usr/local/go/src/testing/testing.go:742 +0x29d                                                                                                 
panic(0x745d20, 0x983920)                                                                                                                                 
        /usr/local/go/src/runtime/panic.go:502 +0x229                                                                                                   
github.com/xorpaul/g10k.TestResolvStatic(0xc42014e0f0)                                                                                                        
        /home/andpaul/dev/go/src/github.com/xorpaul/g10k/g10k_test.go:162 +0x3c8                                                                                                                                     
testing.tRunner(0xc42014e0f0, 0x7c9d88)                                                                                                                                                                              
        /usr/local/go/src/testing/testing.go:777 +0xd0                                                                                                                  
created by testing.(*T).Run                                                                                                                        
        /usr/local/go/src/testing/testing.go:824 +0x2e0                                                                                                                                                              
exit status 2                                                                                                                                     
```

Mainly in the `TestResolvStatic` test

```
go test -v -test.run=TestResolvStatic
```

**Comment by juliantaylor** [comment]
the test succeeds for me.
did you apply the patch an inside the for loop? If I do that I get the same error.
I can create a pull request if you are considering the patch.

**Comment by xorpaul** [comment]
I can recheck, if I've made a mistake.
But yes, a pull request makes it easier to test these things ;)
